<a href="https://colab.research.google.com/github/Melikeda/PythonLibraries/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**The Basics**

In [15]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [5]:
b = np.array([[3.3, 4.4, 5.5],[6.6, 7.7, 8.8]])
print(b)

[[3.3 4.4 5.5]
 [6.6 7.7 8.8]]


In [9]:
# Get Dimesion
a.ndim

1

In [10]:
# Get Dimesion
b.ndim

2

In [11]:
# Get Shape
b.shape

(2, 3)

In [16]:
# Get Type
a.dtype

dtype('int16')

In [20]:
# Get Size
a.itemsize

2

In [21]:
# Get Total Size
a.size

3

In [24]:
# a.size * a.itemsize
a.nbytes

6

**Accessing / Changing specific elements, rows, columns, ect**

In [26]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
# Get a specific element [r,c]
a[1,5]

np.int64(13)

In [30]:
# Get a specific element [r,c]
a[1,-2]

np.int64(13)

In [31]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [34]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [35]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [36]:
a[:, 2] = [5,5]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


**3-d example**

In [41]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
# Get specific element
b[1,1,1]

np.int64(8)

In [44]:
# Replace
b[:,1,:]

array([[3, 4],
       [7, 8]])

**Initializing Different Type of Arrays**

In [45]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [46]:
# All 1s matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [51]:
# Random decimal numbers
np.random.rand(3,2)

array([[0.90262479, 0.8071477 ],
       [0.55046301, 0.33394875],
       [0.78056882, 0.12547923]])

In [57]:
# Random integer values
np.random.randint(6, size=(3,2))

array([[5, 2],
       [3, 0],
       [3, 1]])

In [59]:
# THe identity matrix
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [65]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3)
print(r1)


[1 1 1 2 2 2 3 3 3]


In [68]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [74]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [75]:
# Copy
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print (b)

[100   2   3]


**Mathematics**

In [76]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [77]:
a+2

array([3, 4, 5, 6])

In [78]:
a-2

array([-1,  0,  1,  2])

In [79]:
a*3

array([ 3,  6,  9, 12])

In [80]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [82]:
a **3

array([ 1,  8, 27, 64])

In [81]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [83]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [84]:
# Take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

**Linear Algebra**

In [90]:
a = np.ones((2,3))
print(a)

b = np.full ((3,2), 9)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[9 9]
 [9 9]
 [9 9]]


array([[27., 27.],
       [27., 27.]])

**Statistic**

In [93]:
stats = np.array ([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
np.min(stats)

np.int64(1)

In [95]:
np.sum(stats)

np.int64(21)

In [97]:
np.sum(stats, axis=0)

array([5, 7, 9])